# Generated by Django 4.2.11 on 2024-06-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('child_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=300)),
                ('min_age_in_month', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_vaccine.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('next_vaccine_id', models.CharField(max_length=50)),
                ('next_vaccine_date', models.DateTimeField()),
                ('last_vaccine_date', models.DateTimeField()),
                ('last_vaccination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_vaccine.vaccinations')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_vaccine.user')),
            ],
        ),
    ]
