# Generated by Django 4.2.11 on 2024-06-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='min_age_in_month',
            field=models.IntegerField(),
        ),
    ]
