# Generated by Django 4.2.11 on 2024-06-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_vaccine', '0002_alter_vaccine_min_age_in_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='exmaple@emaple.com', max_length=300),
            preserve_default=False,
        ),
    ]
