# Generated by Django 4.2.11 on 2024-06-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_vaccine', '0005_child_country_child_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='last_vaccination_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_vaccine.vaccinations'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_vaccine_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='next_vaccine_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='next_vaccine_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
