# Generated by Django 4.2.11 on 2024-06-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_vaccine', '0006_alter_child_last_vaccination_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='user',
            name='child_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username',)},
        ),
    ]
