# Generated by Django 4.2.11 on 2024-06-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_vaccine', '0008_rename_child_name_user_childname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
    ]
