# Generated by Django 4.2.11 on 2024-06-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_vaccine', '0009_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username',)},
        ),
    ]
